#!/usr/bin/env bash
# ============================================================================
# Post-build helper for the Linux GenieAPIService package.
#
# Why this exists
# ---------------
# The GenieAPIService bundle that the CMake POST_BUILD step assembles into
# Service/GenieService_v<VERSION>/ is shared between Windows and Linux. The
# bundled htp_backend_ext_config.json under config/ was authored for Windows
# (Snapdragon X Elite class, soc_id=60, dsp_arch=v73) and is **wrong for
# almost any other platform**. We regenerate it here, in the Linux output
# tree only, with the dsp_arch the user requested via QAI_HEXAGONARCH.
#
# We deliberately do NOT touch the per-model config.json files. Their path
# strings (tokenizer.json, ctx-bins, etc.) are end-user data: the user will
# upload the package to their target device and edit those paths to match
# wherever they actually placed the model on disk. See BUILD_LINUX.md for
# the deployment checklist.
#
# Usage (called automatically by build_linux.sh after a successful build):
#   post_build_linux.sh <output_dir> <hexagon_arch_number>
#
# Example:
#   post_build_linux.sh /.../GenieService_v2.1.4 73
# ============================================================================
set -euo pipefail

OUT_DIR="${1:?usage: $0 <output_dir> <hexagon_arch_number>}"
HEX_ARCH="${2:?usage: $0 <output_dir> <hexagon_arch_number>}"
HEX_ARCH="${HEX_ARCH#v}"
HEX_ARCH="${HEX_ARCH#V}"

if [[ ! -d "${OUT_DIR}" ]]; then
    echo "[ERROR] post_build_linux: output dir '${OUT_DIR}' does not exist" >&2
    exit 1
fi

CONFIG_ROOT="${OUT_DIR}/config"
mkdir -p "${CONFIG_ROOT}"

# ---------------------------------------------------------------------------
# Generate htp_backend_ext_config.json under config/ for the requested DSP
# arch. We deliberately omit soc_id so QNN can auto-detect it at runtime,
# which is the most portable default. If the user is targetting a SoC where
# auto-detection fails (rare), they can edit this file post-deploy.
# ---------------------------------------------------------------------------
HTP_EXT="${CONFIG_ROOT}/htp_backend_ext_config.json"
echo "[*] post_build_linux: writing ${HTP_EXT} for v${HEX_ARCH}"

cat > "${HTP_EXT}" <<JSON
{
  "//": "Auto-generated by post_build_linux.sh. The Windows bundle ships a v73 / soc_id=60 file; this Linux version sets dsp_arch to match QAI_HEXAGONARCH and lets QNN auto-detect soc_id at runtime. Add a 'soc_id' field manually if your platform requires it.",
  "devices": [
    {
      "dsp_arch": "v${HEX_ARCH}",
      "cores": [
        {
          "perf_profile": "burst",
          "rpc_control_latency": 100
        }
      ]
    }
  ]
}
JSON

echo "[OK] post_build_linux: done."
